name: Deploy to Vercel

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      # If you have dependencies, uncomment this section
      # - name: Install dependencies
      #   run: npm install

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v21  # Updated to v21
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
